### ISSUE TITLE
Create UPF bundle architecture

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#318]
## WHO: 
- dev. team
- telco core management and support engineers

## WHAT: 
- Create and describe eUPF bundle architecture including but not limited to: 
  - UPF
  - DPI
  - NAT
  - IPS/IDS (optionally)
  - CEM (optionally)
- Prove selected architecture and service chain options

## WHY: 
По результатам поездки в Казахстан появилась гипотеза, что продукт будет ценен как конечное решение, которое оператор поставил и забыл. Типовой состав dataplane бандла на текущей момент, как правило, включает следующее:
Bundle should include these buiding blocks:

## Критерии
1. Необходимо продумать архитектуру конечного продукта, с учетом того, что:
    1. Building blocks could be implemented on different levels (apps, libs or self-coded).
    2. eUPF и его окружающие функции мы пока видим как работающие в kubernetes кластерах
    3. UPF будет нашим продуктом, однако DPI и NAT мы, вероятно, будем брать со стороны.
2. По результатам выполнения этого issue нужно propose several variants and procs + cons for each option. Оценка вариантов может производится по следующим критериям:
    1. Сохранение нормального процесса развертывания, без костылей
    2. Service-chain архитектура, возможность замены одного из модулей на аналогичный без существенной переделки всего бандла
3. Если потребуется сделать рабочий комплект, то на старте 
4. Как продемонстрировать результат:
    1. Рассказ для команды с плюсами-минусами каждого подхода
    2. Возможно, демонстрация "готового" комплекта, если один из подходов во время проработки явно имеет перевес в преимуществах. Можно взять ndpi как DPI и ??? какой-нибудь NAT (обсуждаемо) ???. 
    3. Материалы рассказа из п.1 должны сохраниться где-то в Miro или discussions в проекте. 

I +
N +
V  +
E  ?
S  ?
T  +

## Subtasks
- [x] Investigate best practices to create data service chains with and without k8s | L
- [x] Evaluate 2-3 best options to develop eUPF bundle | M
- [ ] Implement test service chain with eUPF, nDPI and some NAT | L

**Comment by ewdss** [comment]
Add scenarios description and success conditions.
